### ISSUE TITLE
Installation fails for ØMQ v4.1.0-rc1

### ISSUE THREAD

**Issue by phuedx** [plu/zeromq-cookbook#6]
The `zeromq compile and install` step fails because `zeromq-4.0.1-rc1.tar.gz` is extracted to `/usr/local/src/zeromq-4.0.1` and not `/usr/local/src/zeromq-4.0.1-rc1`.

The most flexible fix would be to make the [expected source directory][0] configurable. Simply discarding the `-rc1` suffix would work too.

[0]: https://github.com/plu/zeromq-cookbook/blob/master/recipes/install_from_source.rb#L48

**Comment by plu** [comment]
Thanks for reporting this issue! I have just pushed a fix (d121cbe10e4533273e4d9e1f4633de59f28bae36) and added 4.0.1-rc1 for testing. Jenkins is still running, once he's happy, I'll cut a new release and upload it to the supermarket.

**Comment by plu** [comment]
Jenkins said: `12:09:13 Finished: SUCCESS`

**Comment by plu** [comment]
1.0.6 is available on the supermarket now :)

**Comment by phuedx** [comment]
LGTM. Thanks for the super-fast fix!
